"""create preparation progress table

Revision ID: 19e2d31fd202
Revises: d9e545963b91
Create Date: 2026-09-19 10:13:21.275402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e2d31fd202'
down_revision: Union[str, Sequence[str], None] = 'd9e545963b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparation_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['preparation_plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_progress_id'), 'preparation_progress', ['id'], unique=False)
    op.create_index(op.f('ix_preparation_progress_plan_item_id'), 'preparation_progress', ['plan_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_progress_plan_item_id'), table_name='preparation_progress')
    op.drop_index(op.f('ix_preparation_progress_id'), table_name='preparation_progress')
    op.drop_table('preparation_progress')
    # ### end Alembic commands ###
