"""create interview questions table

Revision ID: 37dd4e89b13b
Revises: e233bf2d2482
Create Date: 2026-09-18 19:50:49.534086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dd4e89b13b'
down_revision: Union[str, Sequence[str], None] = 'e233bf2d2482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_description_id', 'category', 'question', name='uq_interview_question')
    )
    op.create_index(op.f('ix_interview_questions_category'), 'interview_questions', ['category'], unique=False)
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_description_id'), 'interview_questions', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_resume_id'), 'interview_questions', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_resume_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_job_description_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_category'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
