"""create resume drafts table

Revision ID: 47cd53ca7b23
Revises: 19e2d31fd202
Create Date: 2026-09-19 11:11:55.422058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cd53ca7b23'
down_revision: Union[str, Sequence[str], None] = '19e2d31fd202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_drafts_id'), 'resume_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_resume_drafts_job_description_id'), 'resume_drafts', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_drafts_source_resume_id'), 'resume_drafts', ['source_resume_id'], unique=False)
    op.create_index(op.f('ix_resume_drafts_user_id'), 'resume_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_drafts_user_id'), table_name='resume_drafts')
    op.drop_index(op.f('ix_resume_drafts_source_resume_id'), table_name='resume_drafts')
    op.drop_index(op.f('ix_resume_drafts_job_description_id'), table_name='resume_drafts')
    op.drop_index(op.f('ix_resume_drafts_id'), table_name='resume_drafts')
    op.drop_table('resume_drafts')
    # ### end Alembic commands ###
