"""add structured resume data

Revision ID: 5f3a35c31229
Revises: 9eecf9ff63df
Create Date: 2026-09-17 19:36:54.574749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f3a35c31229'
down_revision: Union[str, Sequence[str], None] = '9eecf9ff63df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('structured_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'structured_at')
    op.drop_column('resumes', 'structured_data')
    # ### end Alembic commands ###
