"""create skill gaps table

Revision ID: 652476ca9557
Revises: ef11b7080f30
Create Date: 2026-09-18 14:12:01.670938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652476ca9557'
down_revision: Union[str, Sequence[str], None] = 'ef11b7080f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=False),
    sa.Column('job_description_skill_id', sa.Integer(), nullable=False),
    sa.Column('resume_skill_id', sa.Integer(), nullable=True),
    sa.Column('gap_type', sa.String(length=30), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_description_skill_id'], ['job_description_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_skill_id'], ['resume_skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_id'), 'skill_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_job_description_id'), 'skill_gaps', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_job_description_skill_id'), 'skill_gaps', ['job_description_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_resume_id'), 'skill_gaps', ['resume_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_resume_skill_id'), 'skill_gaps', ['resume_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gaps_resume_skill_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_resume_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_job_description_skill_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_job_description_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    # ### end Alembic commands ###
