"""add resume extracted text

Revision ID: 9eecf9ff63df
Revises: 022686843349
Create Date: 2026-09-17 19:04:13.299132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eecf9ff63df'
down_revision: Union[str, Sequence[str], None] = '022686843349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('extracted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_at')
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
