"""create generated resumes table

Revision ID: d622e76bc5a7
Revises: 47cd53ca7b23
Create Date: 2026-09-19 12:24:53.274866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd622e76bc5a7'
down_revision: Union[str, Sequence[str], None] = '47cd53ca7b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['resume_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_resumes_draft_id'), 'generated_resumes', ['draft_id'], unique=False)
    op.create_index(op.f('ix_generated_resumes_id'), 'generated_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_generated_resumes_user_id'), 'generated_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_resumes_user_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_draft_id'), table_name='generated_resumes')
    op.drop_table('generated_resumes')
    # ### end Alembic commands ###
