"""create preparation plan tables

Revision ID: d9e545963b91
Revises: 37dd4e89b13b
Create Date: 2026-09-18 21:47:16.541385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e545963b91'
down_revision: Union[str, Sequence[str], None] = '37dd4e89b13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_plans_id'), 'preparation_plans', ['id'], unique=False)
    op.create_index(op.f('ix_preparation_plans_job_description_id'), 'preparation_plans', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_preparation_plans_resume_id'), 'preparation_plans', ['resume_id'], unique=False)
    op.create_table('preparation_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['preparation_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_plan_items_id'), 'preparation_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_preparation_plan_items_plan_id'), 'preparation_plan_items', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_plan_items_plan_id'), table_name='preparation_plan_items')
    op.drop_index(op.f('ix_preparation_plan_items_id'), table_name='preparation_plan_items')
    op.drop_table('preparation_plan_items')
    op.drop_index(op.f('ix_preparation_plans_resume_id'), table_name='preparation_plans')
    op.drop_index(op.f('ix_preparation_plans_job_description_id'), table_name='preparation_plans')
    op.drop_index(op.f('ix_preparation_plans_id'), table_name='preparation_plans')
    op.drop_table('preparation_plans')
    # ### end Alembic commands ###
