"""create job compatibilities table

Revision ID: e233bf2d2482
Revises: 652476ca9557
Create Date: 2026-09-18 16:21:38.750397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e233bf2d2482'
down_revision: Union[str, Sequence[str], None] = '652476ca9557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=False),
    sa.Column('total_required', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Integer(), nullable=False),
    sa.Column('partial', sa.Integer(), nullable=False),
    sa.Column('missing', sa.Integer(), nullable=False),
    sa.Column('skill_coverage_percentage', sa.Float(), nullable=False),
    sa.Column('semantic_match_percentage', sa.Float(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_description_id', name='uq_job_compatibility_resume_jd')
    )
    op.create_index(op.f('ix_job_compatibilities_id'), 'job_compatibilities', ['id'], unique=False)
    op.create_index(op.f('ix_job_compatibilities_job_description_id'), 'job_compatibilities', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_job_compatibilities_resume_id'), 'job_compatibilities', ['resume_id'], unique=False)
    op.create_unique_constraint('uq_skill_gap_resume_jd_skill', 'skill_gaps', ['resume_id', 'job_description_id', 'job_description_skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_skill_gap_resume_jd_skill', 'skill_gaps', type_='unique')
    op.drop_index(op.f('ix_job_compatibilities_resume_id'), table_name='job_compatibilities')
    op.drop_index(op.f('ix_job_compatibilities_job_description_id'), table_name='job_compatibilities')
    op.drop_index(op.f('ix_job_compatibilities_id'), table_name='job_compatibilities')
    op.drop_table('job_compatibilities')
    # ### end Alembic commands ###
