"""create skill matches table

Revision ID: ef11b7080f30
Revises: d4cceb6eef59
Create Date: 2026-09-18 13:27:40.806088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef11b7080f30'
down_revision: Union[str, Sequence[str], None] = 'd4cceb6eef59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=False),
    sa.Column('resume_skill_id', sa.Integer(), nullable=True),
    sa.Column('job_description_skill_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('matching_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_description_skill_id'], ['job_description_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_skill_id'], ['resume_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_matches_id'), 'skill_matches', ['id'], unique=False)
    op.create_index(op.f('ix_skill_matches_job_description_id'), 'skill_matches', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_skill_matches_job_description_skill_id'), 'skill_matches', ['job_description_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_matches_resume_id'), 'skill_matches', ['resume_id'], unique=False)
    op.create_index(op.f('ix_skill_matches_resume_skill_id'), 'skill_matches', ['resume_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_matches_resume_skill_id'), table_name='skill_matches')
    op.drop_index(op.f('ix_skill_matches_resume_id'), table_name='skill_matches')
    op.drop_index(op.f('ix_skill_matches_job_description_skill_id'), table_name='skill_matches')
    op.drop_index(op.f('ix_skill_matches_job_description_id'), table_name='skill_matches')
    op.drop_index(op.f('ix_skill_matches_id'), table_name='skill_matches')
    op.drop_table('skill_matches')
    # ### end Alembic commands ###
